app = "needle"
primary_region = "ord"

[build]

[deploy]
  release_command = "bin/rails db:prepare"

[env]
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "1"
  RAILS_SERVE_STATIC_FILES = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/up"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  processes = ["worker"]

[processes]
  app = "bin/rails server -p 3000"
  worker = "bin/jobs"
