default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: needle_development
  username: needle
  password: needle
  host: localhost
  port: 25432

test:
  <<: *default
  database: needle_test
  username: needle
  password: needle
  host: localhost
  port: 25432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
